export const DEMO_REPORT_MONTHS = ["2026-01", "2026-02", "2026-03"];

export const demoReports: Record<string, any> = {
  "2026-01": {
    summary: {
      totalAttendance: 12,
      totalCheckIns: 6,
      totalCheckOuts: 6,
      currentlyInHostel: 0,
    },
    dailyAttendance: [
      { label: "1", value: 0 },
      { label: "2", value: 2 },
      { label: "3", value: 1 },
      { label: "4", value: 0 },
      { label: "5", value: 3 },
      { label: "6", value: 2 },
      { label: "7", value: 4 },
      { label: "8", value: 0 },
      { label: "9", value: 0 },
      { label: "10", value: 0 },
      { label: "11", value: 0 },
      { label: "12", value: 0 },
      { label: "13", value: 0 },
      { label: "14", value: 0 },
      { label: "15", value: 0 },
      { label: "16", value: 0 },
      { label: "17", value: 0 },
      { label: "18", value: 0 },
      { label: "19", value: 0 },
      { label: "20", value: 0 },
      { label: "21", value: 0 },
      { label: "22", value: 0 },
      { label: "23", value: 0 },
      { label: "24", value: 0 },
      { label: "25", value: 0 },
      { label: "26", value: 0 },
      { label: "27", value: 0 },
      { label: "28", value: 0 },
      { label: "29", value: 0 },
      { label: "30", value: 0 },
      { label: "31", value: 0 },
    ],
    roomStatus: {
      available: 8,
      full: 5,
      unavailable: 2,
    },
    needsAttention: {
      studentsWithoutRoom: 0,
      currentlyInStudents: [],
    },
    detailedAttendanceRecords: [
      {
        date: "2026-01-02 07:30 AM",
        student_id: "01-111806",
        name: "Nisa Akandi",
        type: "Check In",
        category: "Weekly",
        notes: "Returned after weekend leave",
        scanned_by: "Demo Warden",
        attendance_type: "check_in",
      },
      {
        date: "2026-01-02 05:45 PM",
        student_id: "01-111806",
        name: "Nisa Akandi",
        type: "Check Out",
        category: "Weekly",
        notes: "Left for approved family visit",
        scanned_by: "Demo Warden",
        attendance_type: "check_out",
      },
      {
        date: "2026-01-05 08:10 AM",
        student_id: "01-111807",
        name: "Alya Syafiqah",
        type: "Check In",
        category: "Sick Leave",
        notes: "Returned after clinic appointment",
        scanned_by: "Demo Warden",
        attendance_type: "check_in",
      },
      {
        date: "2026-01-05 02:20 PM",
        student_id: "01-111807",
        name: "Alya Syafiqah",
        type: "Check Out",
        category: "Sick Leave",
        notes: "Sent to clinic for follow-up",
        scanned_by: "Demo Warden",
        attendance_type: "check_out",
      },
    ],
  },

  "2026-02": {
    summary: {
      totalAttendance: 16,
      totalCheckIns: 9,
      totalCheckOuts: 7,
      currentlyInHostel: 2,
    },
    dailyAttendance: Array.from({ length: 28 }, (_, index) => ({
      label: String(index + 1),
      value: [1, 3, 2, 4, 2, 1, 3][index] || 0,
    })),
    roomStatus: {
      available: 7,
      full: 6,
      unavailable: 2,
    },
    needsAttention: {
      studentsWithoutRoom: 0,
      currentlyInStudents: [
        {
          student_id: "STU001",
          name: "Ahmad Zaki",
          scanned_at: "2026-02-07 07:40 PM",
        },
        {
          student_id: "STU011",
          name: "Nur Aisyah",
          scanned_at: "2026-02-07 08:10 PM",
        },
      ],
    },
    detailedAttendanceRecords: [
      {
        date: "2026-02-03 07:35 AM",
        student_id: "STU001",
        name: "Ahmad Zaki",
        type: "Check In",
        category: "Weekly",
        notes: "Checked in after morning registration",
        scanned_by: "Demo Warden",
        attendance_type: "check_in",
      },
      {
        date: "2026-02-03 06:00 PM",
        student_id: "STU002",
        name: "Muhammad Faris",
        type: "Check Out",
        category: "Hostel Leave",
        notes: "Approved hostel leave",
        scanned_by: "Demo Warden",
        attendance_type: "check_out",
      },
      {
        date: "2026-02-05 08:00 AM",
        student_id: "STU011",
        name: "Nur Aisyah",
        type: "Check In",
        category: "Weekly",
        notes: "Returned to hostel",
        scanned_by: "Demo Warden",
        attendance_type: "check_in",
      },
    ],
  },

  "2026-03": {
    summary: {
      totalAttendance: 20,
      totalCheckIns: 11,
      totalCheckOuts: 9,
      currentlyInHostel: 2,
    },
    dailyAttendance: Array.from({ length: 31 }, (_, index) => ({
      label: String(index + 1),
      value: [2, 2, 5, 3, 1, 4, 3][index] || 0,
    })),
    roomStatus: {
      available: 6,
      full: 7,
      unavailable: 2,
    },
    needsAttention: {
      studentsWithoutRoom: 0,
      currentlyInStudents: [
        {
          student_id: "STU021",
          name: "Emily Tan",
          scanned_at: "2026-03-07 07:20 PM",
        },
        {
          student_id: "STU030",
          name: "Hassan Rafiq",
          scanned_at: "2026-03-07 07:45 PM",
        },
      ],
    },
    detailedAttendanceRecords: [
      {
        date: "2026-03-03 07:45 AM",
        student_id: "STU021",
        name: "Emily Tan",
        type: "Check In",
        category: "Weekly",
        notes: "Returned after weekend leave",
        scanned_by: "Demo Warden",
        attendance_type: "check_in",
      },
      {
        date: "2026-03-03 05:30 PM",
        student_id: "STU030",
        name: "Hassan Rafiq",
        type: "Check Out",
        category: "Emergency Leave",
        notes: "Family emergency leave approved",
        scanned_by: "Demo Warden",
        attendance_type: "check_out",
      },
      {
        date: "2026-03-06 08:15 AM",
        student_id: "01-111809",
        name: "Muhammad Danish",
        type: "Check In",
        category: "Weekly",
        notes: "Checked in after morning inspection",
        scanned_by: "Demo Warden",
        attendance_type: "check_in",
      },
      {
        date: "2026-03-06 06:10 PM",
        student_id: "01-111810",
        name: "Faris Hakimin",
        type: "Check Out",
        category: "Hostel Leave",
        notes: "Approved overnight leave",
        scanned_by: "Demo Warden",
        attendance_type: "check_out",
      },
    ],
  },
};
